-- 0001: change log spine + tenancy + sites + locations.
--
-- Conventions established here and binding for every later migration:
--   * id uuid primary key, generated by the application (UUIDv7).
--   * slug columns follow internal/core/slug; uniqueness expresses the
--     type's declared scope (global vs parent).
--   * status/kind enums are text + CHECK so later migrations can extend
--     them without a type migration.
--   * timestamps are timestamptz; updated_at is maintained by queries.

-- The change log is the append-only record of every mutation, written in
-- the same transaction as the mutation itself. It has no foreign keys to
-- the objects it describes: entries outlive their objects.
CREATE TABLE changelog (
    id           uuid PRIMARY KEY,
    event_at     timestamptz NOT NULL DEFAULT now(),
    actor        text        NOT NULL DEFAULT 'system',
    action       text        NOT NULL CHECK (action IN ('create', 'update', 'delete')),
    object_type  text        NOT NULL,
    object_id    uuid        NOT NULL,
    object_label text        NOT NULL,
    data_before  jsonb,
    data_after   jsonb
);

-- UUIDv7 ids are time-ordered, so ordering by id is ordering by time.
CREATE INDEX changelog_object_idx ON changelog (object_type, object_id, id DESC);

CREATE TABLE tenants (
    id          uuid PRIMARY KEY,
    slug        text        NOT NULL UNIQUE,  -- scope: global
    name        text        NOT NULL,
    description text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sites (
    id          uuid PRIMARY KEY,
    slug        text        NOT NULL UNIQUE,  -- scope: global (sites are path roots)
    name        text        NOT NULL,
    status      text        NOT NULL DEFAULT 'active'
                CHECK (status IN ('planned', 'staging', 'active', 'decommissioning', 'retired')),
    tenant_id   uuid        REFERENCES tenants (id),
    facility    text        NOT NULL DEFAULT '',
    time_zone   text        NOT NULL DEFAULT '',
    description text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sites_tenant_idx ON sites (tenant_id);

-- Locations form one tree per site (buildings, floors, rooms, rows, …).
-- Slug scope: parent location, or the site for roots — two sites can both
-- have a "row-1". The (id, site_id) unique key plus the composite parent
-- foreign key guarantees a parent always belongs to the same site, so the
-- tree can never span sites.
CREATE TABLE locations (
    id          uuid PRIMARY KEY,
    site_id     uuid        NOT NULL REFERENCES sites (id) ON DELETE CASCADE,
    parent_id   uuid,
    slug        text        NOT NULL,
    name        text        NOT NULL,
    kind        text        NOT NULL DEFAULT 'area'
                CHECK (kind IN ('building', 'floor', 'room', 'aisle', 'row', 'cage', 'area')),
    status      text        NOT NULL DEFAULT 'active'
                CHECK (status IN ('planned', 'staging', 'active', 'decommissioning', 'retired')),
    tenant_id   uuid        REFERENCES tenants (id),
    description text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (site_id, parent_id, slug),
    UNIQUE (id, site_id),
    FOREIGN KEY (parent_id, site_id) REFERENCES locations (id, site_id)
);

CREATE INDEX locations_parent_idx ON locations (parent_id);
CREATE INDEX locations_tenant_idx ON locations (tenant_id);
